# Generated by Django 3.0.8 on 2020-07-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img',
        ),
        migrations.AddField(
            model_name='author',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='post'),
        ),
    ]
